### ISSUE TITLE
how to convert the NMEA  message to xy cordinate and position ?

### ISSUE THREAD

**Issue by GaneshGovind1** [MapIV/localization_evaluation_toolkit#1]
Z2�U������������!�46y8�\AO!�-$GNRMC,142821.00,A,4628.60678,N,01119.68747,E,0.065,,010822,,,A,V*17A
$GNVTG,,T,,M,0.065,N,0.121,K,A*3C
$GNGGA,142821.00,4628.60678,N,01119.68747,E,1,08,1.47,275.0,M,46.0,M,,*43
$GNGSA,A,3,01,04,21,09,19,03,,,,,,,2.51,1.47,2.03,1*00
$GNGSA,A,3,87,72,,,,,,,,,,,2.51,1.47,2.03,2*0D
$GNGSA,A,3,,,,,,,,,,,,,2.51,1.47,2.03,3*06
$GNGSA,A,3,,,,,,,,,,,,,2.51,1.47,2.03,4*01
$GPGSV,2,1,08,01,40,147,33,03,67,061,25,04,75,183,34,09,40,219,28,1*6C
$GPGSV,2,2,08,17,35,251,27,19,35,283,22,21,18,147,29,31,23,053,15,1*6A
$GPGSV,1,1,03,01,40,147,24,04,75,183,25,09,40,219,23,6*5C
$GLGSV,1,1,03,71,27,050,26,72,71,359,31,87,67,220,32,1*48
$GLGSV,1,1,04,71,27,050,20,72,71,359,23,,,,18,,,,21,3*7D
$GAGSV,1,1,01,10,,,38,7*78
$GBGSV,1,1,00,0*77
$GNGLL,4628.60678,N,01119.68747,E,142821.00,A,A*7E
�b;(ء"iv�>�&>Nn��@���b\ء�b\����X߈�6˳92�X������������!�46�k8�\AO!*�$GNRMC,142822.00,A,4628.60679,N,01119.68748,E,0.064,,010822,,,A,V*1B
$GNVTG,,T,,M,0.064,N,0.119,K,A*36
$GNGGA,142822.00,4628.60679,N,01119.68748,E,1,08,1.47,275.0,M,46.0,M,,*4E
$GNGSA,A,3,01,04,21,09,19,03,,,,,,,2.51,1.47,2.03,1*00
$GNGSA,A,3,87,72,,,,,,,,,,,2.51,1.47,2.03,2*0D
$GNGSA,A,3,,,,,,,,,,,,,2.51,1.47,2.03,3*06
$GNGSA,A,3,,,,,,,,,,,,,2.51,1.47,2.03,4*01
$GPGSV,2,1,07,01,40,147,33,03,67,061,25,04,75,183,34,09,40,219,28,1*63
$GPGSV,2,2,07,17,35,251,27,19,35,283,22,21,18,147,30,1*5C
$GPGSV,1,1,03,01,40,147,23,04,75,183,25,09,40,219,23,6*5B
$GPGSV,1,1,01,31,23,053,,0*51
$GLGSV,1,1,03,71,27,050,26,72,71,359,31,87,67,220,32,1*48
$GLGSV,1,1,04,71,27,050,18,72,71,359,24,87,67,220,22,,,,18,3*4C
$GAGSV,1,1,01,10,,,38,7*78
$GBGSV,1,1,00,0*77
$GNGLL,4628.60679,N,01119.68748,E,142822.00,A,A*73
�b;(��#kv�=�&<Nn
HB�b\����+W݈�4˳� 2�[������������!�46�8�\AO!�#$GNRMC,142823.00,A,4628.60678,N,01119.68747,E,0.064,,010822,,,A,V*14
$GNVTG,,T,,M,0.064,N,0.119,K,A*36
$GNGGA,142823.00,4628.60678,N,01119.68747,E,1,08,1.47,275.0,M,46.0,M,,*41
$GNGSA,A,3,01,04,21,09,19,03,,,,,,,2.51,1.47,2.03,1*00
$GNGSA,A,3,87,72,,,,,,,,,,,2.51,1.47,2.03,2*0D
$GNGSA,A,3,,,,,,,,,,,,,2.51,1.47,2.03,3*06
$GNGSA,A,3,,,,,,,,,,,,,2.51,1.47,2.03,4*01
$GPGSV,2,1,07,01,40,147,33,03,67,061,25,04,75,183,34,09,40,219,28,1*63
$GPGSV,2,2,07,17,35,251,27,19,35,283,22,21,18,147,30,1*5C
$GPGSV,1,1,03,01,40,147,24,04,75,183,25,09,40,219,24,6*5B
$GPGSV,1,1,01,31,23,053,,0*51
$GLGSV,1,1,04,71,27,050,26,72,71,359,31,87,67,220,32,,,,19,1*47
$GLGSV,1,1,04,71,27,050,19,72,71,359,24,87,67,220,20,,,,18,3*4F
$GAGSV,1,1,01,10,,,38,7*78
$GBGSV,1,1,00,0*77
$GNGLL,4628.60678,N,01119.68747,E,142823.00,A,A*7C
�b;(��$nv�=�&:Nn
-���>�b\����@Vڈ�1˳��1�^������������!�46��7�\AO!TP$GNRMC,142824.00,A,4628.60676,N,01119.68745,E,0.064,,010822,,,A,V*1F
$GNVTG,,T,,M,0.064,N,0.119,K,A*36
$GNGGA,142824.00,4628.60676,N,01119.68745,E,1,08,1.47,274.9,M,46.0,M,,*42
$GNGSA,A,3,01,04,21,09,19,03,,,,,,,2.51,1.47,2.03,1*00
$GNGSA,A,3,87,72,,,,,,,,,,,2.51,1.47,2.03,2*0D
$GNGSA,A,3,,,,,,,,,,,,,2.51,1.47,2.03,3*06
$GNGSA,A,3,,,,,,,,,,,,,2.51,1.47,2.03,4*01
$GPGSV,2,1,07,01,40,147,33,03,67,061,25,04,75,183,34,09,40,219,28,1*63
$GPGSV,2,2,07,17,35,251,27,19,35,283,22,21,18,147,30,1*5C
$GPGSV,1,1,03,01,40,147,24,04,75,183,25,09,40,219,23,6*5C
$GPGSV,1,1,01,31,23,053,,0*51
$GLGSV,1,1,04,71,27,050,25,72,71,000,31,87,67,220,32,,,,18,1*4A
$GLGSV,1,1,04,71,27,050,18,72,71,000,23,87,67,220,19,,,,17,3*43
$GAGSV,1,1,01,10,,,38,7*78
$GBGSV,1,1,00,0*77
$GNGLL,4628.60676,N,01119.68745,E,142824.00,A,A*77
�b;(��%pv�=�&9Nn����c�2022/08/01 14:28:43 [CC---]      19334 B    7748 bps (0) 10.11.136.106
�b\x���UU؈�/˳��1�`������������!�46�7�\AO!��$GNRMC,142825.00,A,4628.60675,N,01119.68744,E,0.064,,010822,,,A,V*1C
$GNVTG,,T,,M,0.064,N,0.119,K,A*36
$GNGGA,142825.00,4628.60675,N,01119.68744,E,1,08,1.47,274.9,M,46.0,M,,*41
$GNGSA,A,3,01,04,21,09,19,03,,,,,,,2.51,1.47,2.03,1*00
$GNGSA,A,3,87,72,,,,,,,,,,,2.51,1.47,2.03,2*0D
$GNGSA,A,3,,,,,,,,,,,,,2.51,1.47,2.03,3*06
$GNGSA,A,3,,,,,,,,,,,,,2.51,1.47,2.03,4*01
$GPGSV,2,1,07,01,40,147,33,03,67,061,25,04,75,183,34,09,40,219,28,1*63
$GPGSV,2,2,07,17,35,251,27,19,35,283,22,21,18,147,30,1*5C
$GPGSV,1,1,01,03,67,061,15,5*50
$GPGSV,1,1,03,01,40,147,24,04,75,183,25,09,40,219,24,6*5B
$GPGSV,1,1,01,31,23,053,,0*51
$GLGSV,1,1,04,71,27,050,25,72,71,000,31,87,67,220,31,,,,17,1*46
$GLGSV,1,1,04,71,27,050,19,72,71,000,24,87,67,220,19,,,,17,3*45
$GAGSV,1,1,01,10,,,38,7*78
$GBGSV,1,1,00,0*77
$GNGLL,4628.60675,N,01119.68744,E,142825.00,A,A*74
�b;(x�&rv�=�&7Nn��
                  ����b\`����iT܈�/˳��1�d������������!�46~�7�\AO!k�$GNRMC,142826.00,A,4628.60675,N,01119.68746,E,0.064,,010822,,,A,V*1D
$GNVTG,,T,,M,0.064,N,0.118,K,A*37
$GNGGA,142826.00,4628.60675,N,01119.68746,E,1,08,1.47,274.8,M,46.0,M,,*41
$GNGSA,A,3,01,04,21,09,19,03,,,,,,,2.51,1.47,2.03,1*00
$GNGSA,A,3,87,72,,,,,,,,,,,2.51,1.47,2.03,2*0D
$GNGSA,A,3,,,,,,,,,,,,,2.51,1.47,2.03,3*06
$GNGSA,A,3,,,,,,,,,,,,,2.51,1.47,2.03,4*01
$GPGSV,2,1,07,01,40,147,33,03,67,061,26,04,75,183,34,09,40,219,28,1*60
$GPGSV,2,2,07,17,35,251,27,19,35,283,21,21,18,147,30,1*5F
$GPGSV,1,1,01,19,35,283,14,5*53
$GPGSV,1,1,04,01,40,147,24,03,67,061,14,04,75,183,25,09,40,219,24,6*6C
$GPGSV,1,1,01,31,23,053,,0*51
$GLGSV,1,1,04,71,27,050,25,72,71,000,31,87,67,220,32,,,,16,1*44
$GLGSV,1,1,02,72,71,000,24,,,,19,3*45
$GAGSV,1,1,01,10,,,38,7*78
$GBGSV,1,1,00,0*77
$GNGLL,4628.60675,N,01119.68746,E,142826.00,A,A*75
�b;(`�'uv�<�&5Nn-���:�b\H��~S܈�/˳�|1�i������������ �46�7�\AO!�I$GNRMC,142827.00,A,4628.60674,N,01119.68746,E,0.063,,010822,,,A,V*1A
$GNVTG,,T,,M,0.063,N,0.117,K,A*3F
$GNGGA,142827.00,4628.60674,N,01119.68746,E,1,08,1.47,274.8,M,46.0,M,,*41
$GNGSA,A,3,01,04,21,09,19,03,,,,,,,2.51,1.47,2.03,1*00
$GNGSA,A,3,87,72,,,,,,,,,,,2.51,1.47,2.03,2*0D
$GNGSA,A,3,,,,,,,,,,,,,2.51,1.47,2.03,3*06
$GNGSA,A,3,,,,,,,,,,,,,2.51,1.47,2.03,4*01
$GPGSV,2,1,07,01,40,147,33,03,67,061,25,04,75,183,34,09,40,219,27,1*6C
$GPGSV,2,2,07,17,35,251,26,19,35,283,21,21,18,147,30,1*5E
$GPGSV,1,1,01,19,35,283,11,5*56
$GPGSV,1,1,04,01,40,147,24,03,67,061,14,04,75,183,26,09,40,219,24,6*6F
$GPGSV,1,1,01,31,23,053,,0*51
$GLGSV,1,1,04,71,27,050,25,72,71,000,31,87,67,220,32,,,,16,1*44
$GLGSV,1,1,02,72,71,000,24,,,,18,3*44
$GAGSV,1,1,01,10,,,38,7*78
$GBGSV,1,1,00,0*77
$GNGLL,4628.60674,N,01119.68746,E,142827.00,A,A*75
�b;(H�(wv�<�&4Nn�����8~^X�b\0����R�݈�3˳A1�l������������ �46��8 \AO!ص$GNRMC,142828.00,A,4628.60677,N,01119.68747,E,0.062,,010822,,,A,V*16
$GNVTG,,T,,M,0.062,N,0.115,K,A*3C
$GNGGA,142828.00,4628.60677,N,01119.68747,E,1,07,1.70,274.8,M,46.0,M,,*47
$GNGSA,A,3,01,04,21,09,19,,,,,,,,2

**Comment by rsasaki0109** [comment]
Since your question is not about this package, I will close this issue.
