### ISSUE TITLE
6-DoF config file

### ISSUE THREAD

**Issue by scarLiu** [MapIV/localization_evaluation_toolkit#4]
I find if the yaml file evaluation.yaml  in the config has something wrong?  if my data contain Euler, I think the column is 5,6,7 but 12,13,14?

**Comment by KOKIAOKI** [comment]
Thank you for your contact.
You can change the column number in yaml file as you like.
If Euler angle column is 5(roll),6(pitch),7(yaw) in your csv file, change the default number to 5,6,7.

**Comment by scarLiu** [comment]
> Thank you for your contact.
> You can change the column number in yaml file as you like.
> If Euler angle column is 5(roll),6(pitch),7(yaw) in your csv file, change the default number to 5,6,7.

Thank you for your reply!
