### ISSUE TITLE
Some options don't work

### ISSUE THREAD

**Issue by KOKIAOKI** [MapIV/localization_evaluation_toolkit#5]
- degree display
[degree mode has error](https://github.com/MapIV/localization_evaluation_toolkit/blob/master/config/evaluation.yaml#L150)
- covariance input
[it doesn't work](https://github.com/MapIV/localization_evaluation_toolkit/blob/master/config/evaluation.yaml#L173-L177)

**Comment by ppaul12** [comment]
All fixed in pull request #7 .
